In [2]:
#Create a list
list=["apple","orange","pineapple"]

In [3]:
#print the list
print(list)

['apple', 'orange', 'pineapple']


In [4]:
#Define the list
list1 =[1,'C',"New Variable"]

In [5]:
print(list1)

[1, 'C', 'New Variable']


In [6]:
#Get the length of the list
print(len(list1))

3


In [7]:
#find the type of the list
print(type(list1))

<class 'list'>


In [8]:
#arrat also can initialise and print and get the length and type of the array as same as the list
array1=[1,2,3,4,5]
print(array1)
print(len(array1))
print(type(array1))

[1, 2, 3, 4, 5]
5
<class 'list'>


In [9]:
#Access the elements in the array
array=[4,5,6,7]
print(array)

#access
print(array[0])

[4, 5, 6, 7]
4


In [11]:
print(array[3])

7


In [13]:
#append-assign a new value to the array
array2=[12,13,14,15,18,69,2,38,26,38,45]
array2.append(8)
print(array2)

[12, 13, 14, 15, 18, 69, 2, 38, 26, 38, 45, 8]


In [14]:
#pop-remove one element from the array
array2.pop(2)
print(array2)

[12, 13, 15, 18, 69, 2, 38, 26, 38, 45, 8]


In [15]:
#copy-make copy of the array
array4 = array2.copy()
print(array4)

[12, 13, 15, 18, 69, 2, 38, 26, 38, 45, 8]


In [16]:
#count-give number of element in the array
array3=[1,1,2,52,42,4,5,2,1,1,2,5,2,3,5,3,6,5,3,6,25,4,3,5,]
print(array3.count(1))


4


In [17]:
#clear-remove all the elements
array2.clear()
print(array2)

[]


In [18]:
#extends-add all elements from one iterable to the end of another list
oldarray =[1,5,8,6,8,6]
newarray=[1,5,3,5,6]
oldarray.extend(newarray)
print(oldarray)

[1, 5, 8, 6, 8, 6, 1, 5, 3, 5, 6]


In [19]:
#index-find the position of an array
print(array3.index(2))

2


In [20]:
#insert-use to add an element in the specific position
array3.insert(1,5)
print(array3)

[1, 5, 1, 2, 52, 42, 4, 5, 2, 1, 1, 2, 5, 2, 3, 5, 3, 6, 5, 3, 6, 25, 4, 3, 5]


In [21]:
#remove-delete the first occurences of a specific value
array3.remove(5)
print(array3)

[1, 1, 2, 52, 42, 4, 5, 2, 1, 1, 2, 5, 2, 3, 5, 3, 6, 5, 3, 6, 25, 4, 3, 5]


In [22]:
#sort-ascending or descending order
array3.sort()
print(array3)


[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 6, 6, 25, 42, 52]


In [25]:
#numpy-dealing with numerical values
import numpy as np


In [26]:
list=[1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
#Converted to the numerical value
np_array=np.array(list)
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
import numpy as np
list1 =["banana","apple","pineapple"]
list1
np_array=np.array(list1)
np_array


array(['banana', 'apple', 'pineapple'], dtype='<U9')

In [31]:
import numpy as np
#create a two dimensional array
#Initialize th num of rows and cols
rows =3
cols=3

#input array elements
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
print(matrix)
matrix1

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]